version: '3'

services:
  nats-server:
    image: nats:latest
    container_name: nats-server
    ports:
      - "8222:8222"

  client-gateway:
    build:
      context: ./client-gateway
      dockerfile: Dockerfile
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - ./client-gateway/.env
    depends_on:
      - nats-server
  
  products-ms:
    build:
      context: ./products-ms
      dockerfile: Dockerfile
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - ./products-ms/.env
    depends_on:
      - nats-server

  orders-ms:
    build:
      context: ./orders-ms
      dockerfile: Dockerfile
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: yarn start:dev
    env_file:
      - ./orders-ms/.env
    depends_on:
      - nats-server
      - orders-db

  orders-db:
    image: postgres:16.2
    container_name: orders_database
    privileged: true
    ports:
      - 5412:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=ordersdb
    volumes:
      - ./postgres:/var/lib/postgresql/data      
    